/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as attackSol from "./Attack.sol";
export type { attackSol };
export type { InsecureEtherVault } from "./InsecureEtherVault";
export type { SecureEtherVault } from "./SecureEtherVault";
