/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "Attack",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Attack__factory>;
    getContractFactory(
      name: "IVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.IVault__factory>;
    getContractFactory(
      name: "InsecureEtherVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.InsecureEtherVault__factory>;
    getContractFactory(
      name: "SecureEtherVault",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.SecureEtherVault__factory>;

    getContractAt(
      name: "Initializable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer,
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "Attack",
      address: string | ethers.Addressable,
      signer?: ethers.Signer,
    ): Promise<Contracts.Attack>;
    getContractAt(
      name: "IVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer,
    ): Promise<Contracts.IVault>;
    getContractAt(
      name: "InsecureEtherVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer,
    ): Promise<Contracts.InsecureEtherVault>;
    getContractAt(
      name: "SecureEtherVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer,
    ): Promise<Contracts.SecureEtherVault>;

    deployContract(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "Attack",
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.Attack>;
    deployContract(
      name: "IVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.IVault>;
    deployContract(
      name: "InsecureEtherVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.InsecureEtherVault>;
    deployContract(
      name: "SecureEtherVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.SecureEtherVault>;

    deployContract(
      name: "Initializable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "Attack",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.Attack>;
    deployContract(
      name: "IVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.IVault>;
    deployContract(
      name: "InsecureEtherVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.InsecureEtherVault>;
    deployContract(
      name: "SecureEtherVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.SecureEtherVault>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer,
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer,
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<ethers.Contract>;
  }
}
